exam:
  duration: 1
  question_number: 5
  time_out: 0
  sort_by_date: "created_at desc"
number_answers: 1
questionStatusActive: active
questionStatusinActive: inactive
seconds: 60
question_type:
  single: "single"
  multiple: "multiple"
  text: "text"
exam_status:
  checked: "checked"
  unchecked: "unchecked"
single: "_single"
multiple: "_multiple"
day: 1
reminder: "Reminder exam"
